---
- name: Install ckb-bench from local source
  copy:
    force: true
    src: "{{ ckb_benchmark_local_source }}"
    dest: "{{ ckb_benchmark_workspace }}/ckb-bench"
    group: ckb
    owner: ckb
    mode: "+x"
  when:
    - ckb_benchmark_local_source is defined and ckb_benchmark_local_source != ''

- name: Install ckb-bench from remote source
  block:
    - name: Download ckb-bench tarball from url
      become: true
      get_url:
        force: true
        url: "{{ ckb_benchmark_download_url }}"
        dest: /tmp/

    - name: Unarchive ckb-bench tarball
      become: true
      unarchive:
        remote_src: true
        src: "/tmp/{{ ckb_benchmark_download_url | basename }}"
        dest: "{{ ckb_benchmark_workspace }}"
        mode: 0777
        extra_opts:
          - --wildcards
          - '*ckb-bench'
          - --transform
          - 's/.*\/ckb-bench$/ckb-bench/'
      when: not ckb_benchmark_download_url.endswith(".7z")

    - name: Unarchive ckb-bench 7z-tarball
      become: true
      shell: |
        7z e -y -o'{{ ckb_benchmark_workspace }}' '/tmp/{{ ckb_benchmark_download_url | basename }}' '*/ckb'
      when: ckb_benchmark_download_url.endswith(".7z")
  when:
    - (ckb_benchmark_local_source is not defined or ckb_benchmark_local_source == '') and ckb_benchmark_download_url is defined
