---
- include: setup.yml
  become: true
  tags:
    - ckb_benchmark_install

- include: install.yml
  become: true
  tags:
    - ckb_benchmark_install

- name: 'Assert must required variables'
  assert:
    that:
      - ckb_benchmark_param is defined

- include: miner.yml
  become: true
  tags:
    - ckb_benchmark_start

- include: bench.yml
  tags:
    - ckb_benchmark_start
