- name: Create ckb group
  become: true
  group:
    name: ckb

- name: Create ckb user
  become: true
  user:
    name: ckb
    group: ckb
    create_home: true
    generate_ssh_key: true

- name: Ensure ckb-bench directories exist
  become: true
  file:
    path: "{{ item }}"
    state: directory
    group: ckb
    owner: ckb
    mode: 0777
  with_items:
    - "{{ ckb_benchmark_workspace }}"
    - "{{ ckb_benchmark_data_dir }}"
